name: 'qs-rust-clippy'
description: 'Rust Clippy (linter)'
author: 'Qernal (https://qernal.com/)'
branding:
  icon: activity
  color: purple

inputs:
  clippy_args:
    description: Arguments for clippy configuration
    required: false
  path_glob:
    description: Glob for path finding (when a repository has multiple rust projects)
    required: false
  git_ssh_key:
    description: Base64 encoded SSH key used for cargo when private git repositories are specified
    required: false
  threads:
    description: Threads to run at once - for concurrency of functions used with `path_glob` (integer)
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/qernal/gh-actions/rust-clippy-x86_64:latest'